name: Haskell CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-haskell@v1
      with:
        ghc-version: '8.10.1'
        cabal-version: '3.2'

    - name: Cache
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - name: apt-getting dependencies
      run: sudo apt-get -y install libsdl2-dev libsndfile1-dev libjack-jackd2-dev llvm
    - name: Install dependencies
      run: |
        cabal new-update
        cabal new-build --only-dependencies --allow-newer=cairo
    - name: Build
      run: cabal new-build --enable-tests --enable-benchmarks --allow-newer=cairo
